# Generated by Django 4.0 on 2021-12-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=50)),
                ('epm_deparment', models.CharField(max_length=100)),
            ],
        ),
    ]
