# Generated by Django 4.0 on 2021-12-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchasetask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=200)),
                ('deaprtment', models.CharField(max_length=225)),
                ('created_by', models.CharField(max_length=50)),
                ('submision_date', models.CharField(default='NOT CHECKED', max_length=250)),
                ('ramark', models.CharField(max_length=100)),
                ('repoting_data', models.CharField(default='datetime.now', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('inprocess', 'INPROCESS')], default='pending', max_length=300)),
                ('checked', models.BooleanField(default=False, max_length=225)),
            ],
        ),
    ]
